plugin.plugin_configuration.elasticsearch_connector.basicauth:
  type: plugin.plugin_configuration.elasticsearch_connector.standard
  label: 'Elasticsearch basic authentication connector settings'
  mapping:
    username:
      type: string
      label: 'Username for HTTP basic authentication'
    password:
      type: string
      label: 'Password for HTTP basic authentication'
