plugin.plugin_configuration.search_api_backend.elasticsearch:
  type: config_object
  label: 'Elasticsearch settings'
  mapping:
    connector:
      type: string
      label: 'The connector plugin ID'
    connector_config:
      type: plugin.plugin_configuration.elasticsearch_connector.[%parent.connector]
    advanced:
      type: mapping
      mapping:
        fuzziness:
          type: string
          label: The fuzziness
        prefix:
          type: string
          label: The index prefix
