plugin.plugin_configuration.elasticsearch_connector.standard:
  type: config_object
  label: 'Elasticsearch standard connector settings'
  mapping:
    url:
      type: string
      label: 'The URL to the Elasticsearch cluster.'
